{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "6.1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.1.15.jar",
          "url": "spring-orm-6.1.15.jar",
          "size": 237915,
          "sha512": "2a932c13d76258fc7bc543a89742b212bd25727b99ae02070206a493be06ee330a0e8ac581d20550663884814918798e503e6f7c3a7d85885a0d1db9f46c00c1",
          "sha256": "780600fdec0a592b5016d76e13dbe723f77e615e400fc43718d1795f0c49fbd1",
          "sha1": "8d52cf2067135de067c52d23ef61f3e1eb8d6a6b",
          "md5": "00f6a2882db2b107ecb8e6bc9fe0143f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.15"
          }
        }
      ],
      "files": [
        {
          "name": "spring-orm-6.1.15.jar",
          "url": "spring-orm-6.1.15.jar",
          "size": 237915,
          "sha512": "2a932c13d76258fc7bc543a89742b212bd25727b99ae02070206a493be06ee330a0e8ac581d20550663884814918798e503e6f7c3a7d85885a0d1db9f46c00c1",
          "sha256": "780600fdec0a592b5016d76e13dbe723f77e615e400fc43718d1795f0c49fbd1",
          "sha1": "8d52cf2067135de067c52d23ef61f3e1eb8d6a6b",
          "md5": "00f6a2882db2b107ecb8e6bc9fe0143f"
        }
      ]
    }
  ]
}
