{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.3.6.jar",
          "url": "spring-boot-starter-3.3.6.jar",
          "size": 4768,
          "sha512": "075827cb56eb71a7c1296cfc07213ba78ce8892c9a5b4edf74c3f6fe54d8cecb6256048796aac0576755e17dda81a34e38c53f22585f1c67ec084a3340db7399",
          "sha256": "3237ba93e033a965a4cccb0e513091c0ac17269108352035bd2ded268c232a97",
          "sha1": "25943d27d244ce54787d7c583a71f63bf62751dc",
          "md5": "9ad11800c47e2eeca31d3aa71786e8ae"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.3.6"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.15"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.3.6.jar",
          "url": "spring-boot-starter-3.3.6.jar",
          "size": 4768,
          "sha512": "075827cb56eb71a7c1296cfc07213ba78ce8892c9a5b4edf74c3f6fe54d8cecb6256048796aac0576755e17dda81a34e38c53f22585f1c67ec084a3340db7399",
          "sha256": "3237ba93e033a965a4cccb0e513091c0ac17269108352035bd2ded268c232a97",
          "sha1": "25943d27d244ce54787d7c583a71f63bf62751dc",
          "md5": "9ad11800c47e2eeca31d3aa71786e8ae"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.3.6-javadoc.jar",
          "url": "spring-boot-starter-3.3.6-javadoc.jar",
          "size": 4768,
          "sha512": "0b9d87459b3e53645cf5244075d689a9871f8329dc9089c6a640e7287287649fb62b90812b9d3e5171d52609086f98a614fdec8dd77d871e345e078e8d974bed",
          "sha256": "78d3c80fb02ab9d9c4cf12dd9c23680210a1504817c2fff3060389227f300a4a",
          "sha1": "32fceac0dcf9c449bd3cf495d675e7346763612a",
          "md5": "91214470b9c3ae6c44d7cd45a17b9789"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.3.6-sources.jar",
          "url": "spring-boot-starter-3.3.6-sources.jar",
          "size": 4768,
          "sha512": "0b9d87459b3e53645cf5244075d689a9871f8329dc9089c6a640e7287287649fb62b90812b9d3e5171d52609086f98a614fdec8dd77d871e345e078e8d974bed",
          "sha256": "78d3c80fb02ab9d9c4cf12dd9c23680210a1504817c2fff3060389227f300a4a",
          "sha1": "32fceac0dcf9c449bd3cf495d675e7346763612a",
          "md5": "91214470b9c3ae6c44d7cd45a17b9789"
        }
      ]
    }
  ]
}
